### ISSUE TITLE
Standard Database-Name

### ISSUE THREAD

**Issue by Mari-Wie** [Mari-Wie/ArchCNL#116]
Every new Execution of the Program creates a new Database (if no DB is given explicitly).
This DB starts with "MW_Test" and ends with a timestamp.

1. The prefix suggest that this is the DB of Mari Wie and should therfore be only "Test".
2. Because of the timestamp suffix, a new Db is createtd with every new execution. It would be better if the old DB would be droped or truncated and a new one would be created (or the empty one re-used)

**Comment by vhschlenker** [comment]
1. Commit fd9f4cd20bb57aa3a284e0aec7357b31792ed895 changes the Prefix to "ArchCNL_", this should avoid any confusion when the Stardog server is also used for other purposes
2. With commit 19511c8efbb051f57bb5e4b88b501b5e27a9bec0 the cli flag "-rm-db" or "--remove-databases" was added. Executing with this flag deletes **all** existing databases. That could maybe be limited to only databases with the "ArchCNL_" prefix.
