### ISSUE TITLE
Add modifiers to local variables

### ISSUE THREAD

**Issue by nizap** [Mari-Wie/ArchCNL#127]
ArchCNL transforms java source code into a code ontology. The contents of this ontology are described in the [wiki](https://github.com/Mari-Wie/ArchCNL/wiki/Code-Model-Ontology). 
Various ontology elements (e.g. methods, parameters, classes) have modifiers (e.g. `public` or `final`) in the ontology.  However, local variables have currently no modifier which contradicts Java code (e.g. `final int myVar;`). This must be changed.

The code model is generated in two steps:
1. Analyze Java source files and extract relevant information. This is implemented in the `java-parser` module. Local variables are treated in `org.archcnl.javaparser.visitors.LocalVariableVisitor`.
2. Transform the relevant information into an OWL ontology. This is implemented in the `owlify-famix` module. The transformation of local variables is implemented in `org.archcnl.owlify.famix.codemodel.LocalVariable`. Modifiers are represented by `org.archcnl.owlify.famix.codemodel.Modifier`.

### Further Guidance

In the `LocalVariableVisitor`, modifiers can be accessed via `VariableDeclarationExpr.getModifiers()`. `org.archcnl.javaparser.visitors.helper.VisitorHelpers` provides a method for transforming the returned modifiers into `Modifier` objects. A list of `Modifier`s must be added to `LocalVariable` and it must be transformed into OWL.  `org.archcnl.owlify.famix.codemodel.Parameter` can be used as an example. The tests must be changed accordingly (fix any errors and add a test case to test the new behavior).
More information on the parsing/transformation procedure is provided [here](https://github.com/Mari-Wie/ArchCNL/wiki/Code-Model-Ontology).

**Comment by nizap** [comment]
PS: The documentation in the wiki must also be updated. To do so, open [this file](https://github.com/Mari-Wie/ArchCNL/blob/master/doc/images/famix-local-variable-ontology) with draw.io, document the modifier (see [here](https://github.com/Mari-Wie/ArchCNL/blob/master/doc/images/famix-parameter-ontology.svg) for an example). Then export the diagram to SVG and update the image file and draw.io file in the repo.  The wiki will automatically load the new image.

**Comment by cmkehler** [comment]
I will look into this
