### ISSUE TITLE
Implement the Ontology Enumeration Pattern for the conformance checking ontology I (OWL Classes)

### ISSUE THREAD

**Issue by nizap** [Mari-Wie/ArchCNL#128]
The module `conformance-checking` is responsible for transforming information on architecture violations into an OWL ontology. This ontology is created from OWL classes, datatype properties and object properties. These elements are provided by the class `org.archcnl.conformancechecking.imp.ConformanceCheckOntologyClassesAndProperties`. The class uses still the "legacy" way to do so. A new way is described by the [Ontology Enumeration Pattern](https://github.com/Mari-Wie/ArchCNL/wiki/Writing-New-Parsers#ontology-enumeration-pattern). An example implementation is found in `org.archcnl.owlify.famix.ontology.FamixOntology` in the module `owlify-famix`.

In this issue, the pattern should be implemented only for OWL classes. Only the methods in  `ConformanceCheckOntologyClassesAndProperties` which return an `Individual` are relevant for this issue. Only the `Classes` enum from the pattern must be implemented. Make sure that the names of the enum members matches the OWL class names **exactly** (see below). Add a factory method for creating individuals of a given enum member (for example as in owlify-famix). The naming scheme of individuals must not be modified. Replace all calls to the relevant methods of `ConformanceCheckOntologyClassesAndProperties` with calls to the new factory method(s). This must be done in both `ConformanceCheckOntology` and its unit test.

When you need more information on OWL ontologies, the [W3 OWL reference](https://www.w3.org/TR/owl-ref/) might help you.

Example:

```java
    public static Individual getConformanceCheckIndividual(OntModel model) {
        OntClass conformanceClass = model.getOntClass(namespace + "ConformanceCheck");
        return model.createIndividual(namespace + "ConformanceCheck", conformanceClass);
    }
```
the following enum member is needed
```java
public enum ConformanceCheckOntClasses {
    ConformanceCheck;

    // example for a factory method, but you are free to use other solutions
    public Individual createIndividual(OntModel model, int number) {
        final String className = ConformanceCheckOntologyClassesAndProperties.getOntologyNamespace() + this.name();
        return model.getOntClass(className).createIndividual(className + number);
    }
}
```

**Comment by h-engelhardt** [comment]
I will work on this.
