### ISSUE TITLE
Implement the Ontology Enumeration Pattern for the conformance checking ontology III (Object Properties)

### ISSUE THREAD

**Issue by nizap** [Mari-Wie/ArchCNL#130]
The module `conformance-checking` is responsible for transforming information on architecture violations into an OWL ontology. This ontology is created from OWL classes, datatype properties and object properties. These elements are provided by the class `org.archcnl.conformancechecking.imp.ConformanceCheckOntologyClassesAndProperties`. The class uses still the "legacy" way to do so. A new way is described by the [Ontology Enumeration Pattern](https://github.com/Mari-Wie/ArchCNL/wiki/Writing-New-Parsers#ontology-enumeration-pattern). An example implementation is found in `org.archcnl.owlify.famix.ontology.FamixOntology` in the module `owlify-famix`.

In this issue, the pattern should be implemented only for OWL datatype properties. Only the methods in  `ConformanceCheckOntologyClassesAndProperties` which return an `ObjectProperty` are relevant for this issue. Only the `ObjectProperties` enum from the pattern must be implemented. Make sure that the names of the enum members matches the property names **exactly** (see below). Add a factory method for instantiating the property associated with a given enum member (for example as in owlify-famix). Replace all calls to the relevant methods of `ConformanceCheckOntologyClassesAndProperties` with calls to the new factory method(s). This must be done in both `ConformanceCheckOntology` and its unit test.

When you need more information on OWL ontologies, the [W3 OWL reference](https://www.w3.org/TR/owl-ref/) might help you.

Example:

```java
    public static ObjectProperty getValidatesProperty(OntModel model) {
        return model.getObjectProperty(namespace + "validates");
    }
```
the following enum member is needed
```java
public enum ConformanceCheckObjectProperties {
    validates;

    // example for a factory method, but you are free to use other solutions
    public ObjectProperty getProperty(OntModel model) {
        return model.getObjectProperty(ConformanceCheckOntologyClassesAndProperties.getOntologyNamespace()  + this.name());
    }
}
```

**Comment by VincentRaudszus** [comment]
I will take a look at this.
