### ISSUE TITLE
Simplify adding new parsers

### ISSUE THREAD

**Issue by nizap** [Mari-Wie/ArchCNL#132]
ArcnCNL applies a plugin architecture. The `toolchain` module is the core and uses the other (plugin) modules. The different plugin modules implement different features and are independent from each other. A key advantage of plugin architectures is that switching individual plugins on/off is easy.

The code model used by ArchCNL is created by plugins implementing the interface `OwlifyComponent` defined in the `owlify` module. Currently, there is only one `OwlifyComponent` (the `java-parser`) but more will be added in the future. Thus, a mechanism for enabling/disabling `OwlifyComponent`s is required. Also, the process of adding new `OwlifyComponent` to the toolchain must be simplified.

One possible solution is replace the single `OwlifyComponent` in `org.archcnl.toolchain.CNLToolchain` (`toolchain` package) with a list of `OwlifyComponent`s. The `buildCodeModel()` method must be called for each item in this list. The resulting models (Apache Jena's `Model` class represents an OWL ontology) can be combined using the `Model.add(Model)` method. The final code model should consist of all the "sum" of all `Model`s generated by the `OwlifyComponent`s.

Additionally, users should be able to select the `OwlifyComponent` which should be executed. This can be done via command line arguments or a config file. Only the selected `OwlifyComponent` should be added to the list. The default configuration should be exactly the same as the current state (only the `java-parser` is executed) to prevent breaking changes. If you want to use command line arguments, `CNLToolchainCLI` is relevant for you.

**Comment by toklinke** [comment]
I will work on this.

**Comment by nizap** [comment]
Update: The `kotlin-parser` has just been merged into master. Thus, this issue must deal with two existing parsers instead of only one.
