### ISSUE TITLE
Reduce code duplication in java-parser visitor tests

### ISSUE THREAD

**Issue by nizap** [Mari-Wie/ArchCNL#133]
The module `java-parser` extracts a code model from Java source files. The visitor pattern is used for these means. Different elements of the code (class/method/field declarations, parameters, local variables, ...) are visited by visitors, which create objects representing these elements. Most of the visitors have a unit test in the `org.archcnl.javaparser.visitors` package (src/test/java).

The visitors work together with the external "javaparser" library. This library requires that the paths to source directories are set in the configuration of a symbol resolver. Else, identifiers cannot be resolved properly. See [here](https://github.com/Mari-Wie/ArchCNL/wiki/Notes-on-the-Java-Parser#setting-up-the-javaparser-and-symbol-resolver) for more information.
This configuration is set once in  `org.archcnl.javaparser.parser.ModelExtractor.setup()` as well as in _each_ visitor unit test. This code duplication must be removed. One possible option is to introduce a factory method which creates the type resolver configuration object from a set of source directory paths.

**Comment by AlexHamburg** [comment]
I will look at it !

**Comment by nizap** [comment]
Closed by #155
