### ISSUE TITLE
Add test cases in ModelExtractorTest

### ISSUE THREAD

**Issue by nizap** [Mari-Wie/ArchCNL#135]
The `java-parser` module is responsible for creating a code model out of analyzed Java source files. This extraction process is controlled (on the topmost layer) by the class `org.archcnl.javaparser.parser.ModelExtractor`. The code model is represented by an aggregate of classes from the module `owlify-famix` as described [here](https://github.com/Mari-Wie/ArchCNL/wiki/Writing-New-Parsers#parsers-for-object-oriented-programming-languages). 

The test class of `ModelExtractor`, `ModelExtractorTest`, analyzes a small example project (it is more of an integration test than a unit test). The model of each analyzed file is verified in its own test case. The `@Before` method extracts these file model objects already to the fields of the test class `classA`, `enumeration`, etc.).

However, only `classA` and `interfacE` are tested. For the other 4 fields/files, no tests exist. The task of this issue is to add these missing tests. The analyzed files are located in the `examples/extractortest` package in the test folder, the switch in `setUp()` maps file names to the fields. Further details on the information extracted by the `ModelExtractor` and stored in the code model as well as its aggregate structure see the Javadoc comments of the model element classes and [this page](https://github.com/Mari-Wie/ArchCNL/wiki/Code-Model-Ontology#famix-parsers).

If you discover any bugs, either add a new issue (please use the bug label) or fix them yourself if you want.

**Comment by GrouchyLaTortue** [comment]
I will look at it !

**Comment by nizap** [comment]
Was done in e1b69c6f825e5518f1aa84c997bf28d598d03931.
