### ISSUE TITLE
Analyse whether replacing XTEND would be beneficial

### ISSUE THREAD

**Issue by nizap** [Mari-Wie/ArchCNL#21]
Research whether there is an alternative with less dependencies.

**Comment by nizap** [comment]
Xtext has been designed to transform files to other files. However, ArchCNL writes the contents of the input file from memory and reads the contents of the output file back to memory. Thus, performance would benefit from transforming rules in memory without any I/O . Xtext seems not to be capable of this. And even if it is, it would be a dirty workaround (see comments of #5). This should be reflected when searching for alternatives.

**Comment by nizap** [comment]
related #126

**Comment by vhschlenker** [comment]
Since #126 is merged, this should be closed, right @nizap ?

**Comment by nizap** [comment]
I think so.
