### ISSUE TITLE
Add Proof Descriptions to the Database/Ontology

### ISSUE THREAD

**Issue by nizap** [Mari-Wie/ArchCNL#57]
When a conformance check is performed, the results are stored into an ontology by the `conformance-checking` module. The enriched ontology is then stored in the data base by the `cnl-toolchain`.

The module is passed a `ConstraintViolationResultSet` which contains `ConstraintViolation` objects. These objects contain further information about identified architecture violations. However, the `conformance-checking` module does not add this information to the ontology.  Only rules of the schema `<Proof> --proofs--> <ArchitectureViolation>` are added, but the `Proof` does not contain any information. 

This information should be added to the ontology by the `conformance-checking` module.

**Comment by nizap** [comment]
Possibly related to #79.

**Comment by Mari-Wie** [comment]
Sounds like a bug to me, doesn't it?
Added bug-lable.
