### ISSUE TITLE
Simplify adding new parsers

### ISSUE THREAD

**Issue by nizap** [Mari-Wie/ArchCNL#80]
Each input parser (the famix parser, the maven parser, etc.) implements the interface `OwlifyComponent`. However, the used parsers are currently "hard-coded" into the toolchain, i.e. they are accessed by their class and not by the interface. This should be changed so that both new parsers can be added and the parsers can be selected more easily.

This requires  
- that the toolchain uses parsers only via `OwlifyComponent` and stores them in some sort of collection,
- that the toolchain executes all stored parsers, and
- that the results are gathered in some appropriate way so that the architecture-to-code mapping does not have to know how many parsers have been used.

**Comment by nizap** [comment]
It might be beneficial to do #72 before starting this issue. If the different parsers do not define "overlapping" ontologies, the Jena library can be used to "merge"/unite the different ontologies.

**Comment by nizap** [comment]
As of today, the module `architecture-reasoning` takes a Jena API `Model` as code model/ontology. This should be changed to a collection of `Models`, which are unified by the class `ArchitectureToCodeMapper` as described above.

**Comment by vhschlenker** [comment]
@nizap 
What do you think would be the best approach to merge the models from the multiple parsers?
So far, I've discovered the `union` or `add` method on a Model as a possibility to merge them.

**Comment by nizap** [comment]
When I understand the [documentation](https://jena.apache.org/documentation/javadoc/jena/org/apache/jena/rdf/model/Model.html#add(org.apache.jena.rdf.model.Model)) correctly, it does not matter whether `add` or `union` is used when the operand models are not used further (union creates a new model, add extends an existing one).

**Comment by nizap** [comment]
The students participating in the master project are supposed to work on some small issues to get into the code. I have added this issue (with some more information on the topic) to the list of these small issues (#132 ). Thus, this issue is a duplicate and can be closed.
