### ISSUE TITLE
Project formatting 

### ISSUE THREAD

**Issue by vhschlenker** [Mari-Wie/ArchCNL#95]
It should be discussed if any sort of common formatting should be required.
This could be in the form of an eclipse [XML import](https://github.com/google/styleguide/blob/gh-pages/eclipse-java-google-style.xml), [an eclipse plugin](https://github.com/google/google-java-format/tree/master/eclipse_plugin) or as a [maven plugin](https://github.com/diffplug/spotless/tree/main/plugin-maven).

The maven plugin option would have the advantage that it could be integrated into the CI process, so there is no further configuration required.

**Comment by nizap** [comment]
Another advantage of the maven plugin is that is works with other IDEs and build tools.
